/**
 * spec-51 — row factories shared by scenarios.
 *
 * Rule 1 of the seed: never write orders.status. It defaults to 'ingresado'
 * (20260313000001) and is thereafter owned by trg_recalculate_order_status.
 * Scenarios insert packages and let the trigger settle, then assert.
 */

import type { SeedClient } from './db';
import { qaId, type ScenarioGroup } from './ids';

export interface OrderSpec {
  group: ScenarioGroup;
  sequence: number;
  operatorId: string;
  orderNumber: string;
  /** Package statuses to create. The order's status is derived from these. */
  packageStatuses: string[];
  customerName?: string;
  comuna?: string;
  deliveryDate?: string;
  importedVia?: string;
  dispatchGuideUrl?: string | null;
  /** The CARGA this order belongs to — matches manifests.external_load_id. */
  externalLoadId?: string | null;
  /** Which client of the operator the order belongs to (Easy, Paris, …). */
  tenantClientId?: string | null;
  /** Where the order is collected from. */
  pickupPointId?: string | null;
  retailerName?: string;
}

export interface CreatedOrder {
  orderId: string;
  orderNumber: string;
  packageIds: string[];
}

/**
 * Resolve a QA login user by email.
 *
 * Several tables reference `public.users` rather than `public.drivers` —
 * notably `pickup_routes.driver_id`, `dock_batches.created_by`,
 * `dock_scans.scanned_by`, `reception_scans.scanned_by` and
 * `route_receptions.delivered_by`. Their ids are generated by
 * create-qa-users.sh rather than fixed, so scenarios look them up by the
 * stable thing: the email.
 *
 * Returns null when the QA users have not been created yet, so a scenario can
 * skip rather than fail with a foreign-key violation.
 */
export async function resolveUserId(
  db: SeedClient,
  email: string,
): Promise<string | null> {
  const rows = await db.query<{ id: string }>(
    'SELECT id FROM public.users WHERE email = $1 AND deleted_at IS NULL LIMIT 1',
    [email],
  );
  return rows[0]?.id ?? null;
}

/** The QA login users created by infra/supabase-qa/create-qa-users.sh. */
export const QA_USERS = {
  PICKUP_CREW: 'qa-pickup-crew@qa.test',
  WAREHOUSE_STAFF: 'qa-warehouse-staff@qa.test',
  LOADING_CREW: 'qa-loading-crew@qa.test',
  OPERATIONS_MANAGER: 'qa-operations-manager@qa.test',
  ADMIN: 'qa-admin@qa.test',
  SUPER_ADMIN: 'qa-super-admin@qa.test',
} as const;

/**
 * Bring an existing login back to a working state: make sure it has the
 * auth.identities row GoTrue needs for password login, and that public.users
 * carries the role's permissions (handle_new_user inserts an empty array).
 * Both steps are idempotent.
 */
async function repairLoginUser(
  db: SeedClient,
  args: { email: string; permissions: string[] },
): Promise<void> {
  const rows = await db.query<{ id: string; has_identity: boolean }>(
    `SELECT u.id,
            EXISTS (SELECT 1 FROM auth.identities i WHERE i.user_id = u.id) AS has_identity
       FROM auth.users u WHERE u.email = $1`,
    [args.email],
  );
  const user = rows[0];
  if (!user) return;

  if (!user.has_identity) {
    await db.query(
      `INSERT INTO auth.identities (
         id, user_id, identity_data, provider, provider_id,
         last_sign_in_at, created_at, updated_at
       ) VALUES (
         gen_random_uuid(), $1::uuid, $2::jsonb, 'email', $3::text, now(), now(), now()
       )`,
      [
        user.id,
        JSON.stringify({
          sub: user.id,
          email: args.email,
          email_verified: true,
          phone_verified: false,
        }),
        user.id,
      ],
    );
  }

  await db.query(
    `UPDATE public.users SET permissions = $2::text[]
      WHERE email = $1 AND deleted_at IS NULL`,
    [args.email, args.permissions],
  );
}

/** Same password as every other QA login (infra/supabase-qa/create-qa-users.sh). */
export const QA_PASSWORD = 'QaTest123!';

const GOTRUE_INSTANCE_ID = '00000000-0000-0000-0000-000000000000';

/**
 * Create a login for a tenant that this seed created.
 *
 * create-qa-users.sh owns the six baseline logins, but it runs BEFORE the
 * scenario seed and derives every address as qa-<role>@qa.test. A user for an
 * operator the seed itself creates has to be made here, after that operator
 * exists, or the foreign key fails.
 *
 * Mirrors that script's SQL deliberately: a row in auth.users (whose
 * handle_new_user trigger creates public.users from raw_app_meta_data), plus
 * the auth.identities row GoTrue v2 needs for password login, plus the role's
 * permissions — handle_new_user inserts an empty array.
 *
 * Empty strings rather than NULL on the token columns; GoTrue errors scanning
 * NULLs there.
 */
export async function createLoginUser(
  db: SeedClient,
  args: {
    id: string;
    operatorId: string;
    email: string;
    role: string;
    fullName: string;
    permissions: string[];
    password?: string;
  },
): Promise<'created' | 'exists'> {
  const existing = await db.query<{ exists: boolean }>(
    'SELECT EXISTS (SELECT 1 FROM auth.users WHERE email = $1) AS exists',
    [args.email],
  );

  // A half-created user is worse than none: if an earlier run inserted
  // auth.users and then failed before auth.identities, the account exists but
  // cannot log in. Returning early on "exists" would leave it broken forever,
  // so repair instead of skipping.
  if (existing[0]?.exists) {
    await repairLoginUser(db, args);
    return 'exists';
  }

  // pgcrypto's schema varies by install; ask rather than assume.
  const ext = await db.query<{ nspname: string }>(
    `SELECT n.nspname FROM pg_extension e
       JOIN pg_namespace n ON n.oid = e.extnamespace
      WHERE e.extname = 'pgcrypto'`,
  );
  const cryptSchema = ext[0]?.nspname ?? 'public';

  const claims = {
    provider: 'email',
    providers: ['email'],
    operator_id: args.operatorId,
    role: args.role,
    claims: { operator_id: args.operatorId, role: args.role },
  };

  // Atomic: an auth.users row without its identity is an account that
  // exists but cannot log in.
  await db.transaction(async (tx) => {
    await tx.query(
      `INSERT INTO auth.users (
         id, instance_id, aud, role, email, encrypted_password, email_confirmed_at,
         raw_app_meta_data, raw_user_meta_data, created_at, updated_at,
         confirmation_token, recovery_token,
         email_change, email_change_token_new, email_change_token_current
       ) VALUES (
         $1, $2, 'authenticated', 'authenticated', $3,
         ${cryptSchema}.crypt($4, ${cryptSchema}.gen_salt('bf', 10)),
         now(), $5::jsonb, $6::jsonb, now(), now(), '', '', '', '', ''
       )`,
      [
        args.id,
        GOTRUE_INSTANCE_ID,
        args.email,
        args.password ?? QA_PASSWORD,
        JSON.stringify(claims),
        JSON.stringify({ full_name: args.fullName }),
      ],
    );

    await tx.query(
      // provider_id is text and user_id is uuid; reusing one placeholder for both
      // makes Postgres fail with "inconsistent types deduced for parameter $1".
      `INSERT INTO auth.identities (
         id, user_id, identity_data, provider, provider_id,
         last_sign_in_at, created_at, updated_at
       ) VALUES (
         gen_random_uuid(), $1::uuid, $2::jsonb, 'email', $3::text, now(), now(), now()
       )`,
      [
        args.id,
        JSON.stringify({
          sub: args.id,
          email: args.email,
          email_verified: true,
          phone_verified: false,
        }),
        args.id,
      ],
    );

    // handle_new_user inserts permissions='{}' — apply the role mapping.
    await tx.query(
      `UPDATE public.users SET permissions = $2::text[]
        WHERE email = $1 AND deleted_at IS NULL`,
      [args.email, args.permissions],
    );

  });

  return 'created';
}

/**
 * Insert an operator. Idempotent on the primary key so a re-run is a no-op.
 */
export async function createOperator(
  db: SeedClient,
  args: { id: string; name: string; slug: string; countryCode?: string },
): Promise<string> {
  await db.query(
    `INSERT INTO public.operators (id, name, slug, country_code, is_active, settings)
     VALUES ($1, $2, $3, $4, TRUE, $5::jsonb)
     ON CONFLICT (id) DO NOTHING`,
    [
      args.id,
      args.name,
      args.slug,
      args.countryCode ?? 'CL',
      JSON.stringify({ branding: { company_name: args.name } }),
    ],
  );
  return args.id;
}

/**
 * Insert an order plus its packages, letting the status trigger derive
 * orders.status. Package ids are allocated from the order's sequence so they
 * stay stable across runs.
 */
/*
 * DO UPDATE, not DO NOTHING, on the identifying columns.
 *
 * Order ids are deterministic -- qaId(group, sequence) -- and the sequence is
 * allocated by walking a scenario's cargas in order. So editing a scenario's
 * composition (moving one order from one carga to the next) re-points a
 * sequence at a different load id, while the row already in the database keeps
 * the old one. With DO NOTHING the edit never propagated and the scenario's own
 * assertions failed against data they could not correct: Musan's PARIS cargas
 * sat at a 3/2 split for weeks while the definition said 4/1.
 *
 * Only the fields a scenario definition owns are updated. Status is left alone
 * -- it is derived from packages by trigger, and resettleOrderStatus() below is
 * what re-derives it -- and so is anything a tester may have changed by using
 * the app, which is the whole reason this seeder is idempotent rather than
 * destructive.
 */
export async function createOrderWithPackages(
  db: SeedClient,
  spec: OrderSpec,
): Promise<CreatedOrder> {
  const orderId = qaId(spec.group, spec.sequence);

  await db.query(
    `INSERT INTO public.orders (
       id, operator_id, order_number, customer_name, customer_phone,
       delivery_address, comuna, delivery_date, retailer_name,
       raw_data, imported_via, imported_at, dispatch_guide_url,
       external_load_id, tenant_client_id, pickup_point_id
     ) VALUES (
       $1, $2, $3, $4, $5, $6, $7, $8, $9, $10::jsonb, $11::imported_via_enum, NOW(), $12,
       $13, $14, $15
     )
     ON CONFLICT (id) DO UPDATE SET
       order_number     = EXCLUDED.order_number,
       external_load_id = EXCLUDED.external_load_id,
       retailer_name    = EXCLUDED.retailer_name,
       tenant_client_id = EXCLUDED.tenant_client_id,
       pickup_point_id  = EXCLUDED.pickup_point_id,
       comuna           = EXCLUDED.comuna`,
    [
      orderId,
      spec.operatorId,
      spec.orderNumber,
      spec.customerName ?? `Cliente ${spec.orderNumber}`,
      '+56900000000',
      `Calle QA ${spec.sequence}`,
      spec.comuna ?? 'Maipú',
      spec.deliveryDate ?? new Date().toISOString().slice(0, 10),
      spec.retailerName ?? 'QA Retail',
      JSON.stringify({ source: 'seed-qa-generator' }),
      spec.importedVia ?? 'MANUAL',
      spec.dispatchGuideUrl ?? null,
      spec.externalLoadId ?? null,
      spec.tenantClientId ?? null,
      spec.pickupPointId ?? null,
    ],
  );

  const packageIds: string[] = [];

  for (let i = 0; i < spec.packageStatuses.length; i++) {
    // Package sequence is derived from the order's so ids stay deterministic
    // and cannot collide with another order in the same group.
    const packageId = qaId(spec.group, spec.sequence * 100 + i + 1);
    packageIds.push(packageId);

    await db.query(
      `INSERT INTO public.packages (
         id, operator_id, order_id, label, status, sku_items, raw_data
       ) VALUES ($1, $2, $3, $4, $5::package_status_enum, $6::jsonb, $7::jsonb)
       ON CONFLICT (id) DO NOTHING`,
      [
        packageId,
        spec.operatorId,
        orderId,
        `${spec.orderNumber}-CTN-${i + 1}`,
        spec.packageStatuses[i],
        JSON.stringify([{ sku: `QA-SKU-${i + 1}`, description: 'Caja QA', quantity: 1 }]),
        JSON.stringify({ source: 'seed-qa-generator' }),
      ],
    );
  }

  return { orderId, orderNumber: spec.orderNumber, packageIds };
}

/**
 * Put an order's packages back to a known starting state.
 *
 * Journeys mutate what they touch, so unlike the other scenarios they are not
 * idempotent by construction: a second run would begin wherever the first one
 * finished. Re-running a failed-delivery journey without this finds its order
 * already at retorno_hub and asserts the wrong starting state.
 *
 * Statuses are applied in label order so package N always gets statuses[N].
 */
export async function resetOrderPackages(
  db: SeedClient,
  orderId: string,
  statuses: string[],
): Promise<void> {
  const packages = await db.query<{ id: string }>(
    `SELECT id FROM public.packages
      WHERE order_id = $1 AND deleted_at IS NULL
      ORDER BY label`,
    [orderId],
  );

  for (let i = 0; i < packages.length && i < statuses.length; i++) {
    await db.query(
      `UPDATE public.packages
          SET status = $2::package_status_enum
        WHERE id = $1`,
      [packages[i].id, statuses[i]],
    );
  }
}

/**
 * Force the trigger to re-derive an order's status.
 *
 * Needed when packages were inserted by an earlier run (ON CONFLICT DO NOTHING
 * means no trigger fires the second time) but we still want to assert the
 * derived state. Touching status with its current value is enough — the
 * trigger fires on UPDATE OF status regardless of whether the value changed.
 */
export async function resettleOrderStatus(db: SeedClient, orderId: string): Promise<void> {
  await db.query(
    `UPDATE public.packages SET status = status
      WHERE order_id = $1 AND deleted_at IS NULL`,
    [orderId],
  );
}
