/**
 * spec-79 review L-4: extracted out of factories.ts (429 lines, over the
 * repo's 300-line cap) — the QA login-user machinery (resolve/create/repair)
 * is a self-contained concern with no dependency on the order/package
 * factories that remain there. Re-exported from factories.ts so no existing
 * import site (journeys.ts, musan.ts, pickup.ts) has to change its path.
 */

import type { SeedClient } from './db';

/**
 * Resolve a QA login user by email.
 *
 * Several tables reference `public.users` rather than `public.drivers` —
 * notably `pickup_routes.driver_id`, `dock_batches.created_by`,
 * `dock_scans.scanned_by`, `reception_scans.scanned_by` and
 * `route_receptions.delivered_by`. Their ids are generated by
 * create-qa-users.sh rather than fixed, so scenarios look them up by the
 * stable thing: the email.
 *
 * Returns null when the QA users have not been created yet, so a scenario can
 * skip rather than fail with a foreign-key violation.
 */
export async function resolveUserId(
  db: SeedClient,
  email: string,
): Promise<string | null> {
  const rows = await db.query<{ id: string }>(
    'SELECT id FROM public.users WHERE email = $1 AND deleted_at IS NULL LIMIT 1',
    [email],
  );
  return rows[0]?.id ?? null;
}

/** The QA login users created by infra/supabase-qa/create-qa-users.sh. */
export const QA_USERS = {
  PICKUP_CREW: 'qa-pickup-crew@qa.test',
  WAREHOUSE_STAFF: 'qa-warehouse-staff@qa.test',
  LOADING_CREW: 'qa-loading-crew@qa.test',
  OPERATIONS_MANAGER: 'qa-operations-manager@qa.test',
  ADMIN: 'qa-admin@qa.test',
  SUPER_ADMIN: 'qa-super-admin@qa.test',
} as const;

/**
 * Bring an existing login back to a working state: make sure it has the
 * auth.identities row GoTrue needs for password login, and that public.users
 * carries the role's permissions (handle_new_user inserts an empty array).
 * Both steps are idempotent.
 */
async function repairLoginUser(
  db: SeedClient,
  args: { email: string; permissions: string[] },
): Promise<void> {
  const rows = await db.query<{ id: string; has_identity: boolean }>(
    `SELECT u.id,
            EXISTS (SELECT 1 FROM auth.identities i WHERE i.user_id = u.id) AS has_identity
       FROM auth.users u WHERE u.email = $1`,
    [args.email],
  );
  const user = rows[0];
  if (!user) return;

  if (!user.has_identity) {
    await db.query(
      `INSERT INTO auth.identities (
         id, user_id, identity_data, provider, provider_id,
         last_sign_in_at, created_at, updated_at
       ) VALUES (
         gen_random_uuid(), $1::uuid, $2::jsonb, 'email', $3::text, now(), now(), now()
       )`,
      [
        user.id,
        JSON.stringify({
          sub: user.id,
          email: args.email,
          email_verified: true,
          phone_verified: false,
        }),
        user.id,
      ],
    );
  }

  await db.query(
    `UPDATE public.users SET permissions = $2::text[]
      WHERE email = $1 AND deleted_at IS NULL`,
    [args.email, args.permissions],
  );
}

/** Same password as every other QA login (infra/supabase-qa/create-qa-users.sh). */
export const QA_PASSWORD = 'QaTest123!';

const GOTRUE_INSTANCE_ID = '00000000-0000-0000-0000-000000000000';

/**
 * Create a login for a tenant that this seed created.
 *
 * create-qa-users.sh owns the six baseline logins, but it runs BEFORE the
 * scenario seed and derives every address as qa-<role>@qa.test. A user for an
 * operator the seed itself creates has to be made here, after that operator
 * exists, or the foreign key fails.
 *
 * Mirrors that script's SQL deliberately: a row in auth.users (whose
 * handle_new_user trigger creates public.users from raw_app_meta_data), plus
 * the auth.identities row GoTrue v2 needs for password login, plus the role's
 * permissions — handle_new_user inserts an empty array.
 *
 * Empty strings rather than NULL on the token columns; GoTrue errors scanning
 * NULLs there.
 */
export async function createLoginUser(
  db: SeedClient,
  args: {
    id: string;
    operatorId: string;
    email: string;
    role: string;
    fullName: string;
    permissions: string[];
    password?: string;
  },
): Promise<'created' | 'exists'> {
  const existing = await db.query<{ exists: boolean }>(
    'SELECT EXISTS (SELECT 1 FROM auth.users WHERE email = $1) AS exists',
    [args.email],
  );

  // A half-created user is worse than none: if an earlier run inserted
  // auth.users and then failed before auth.identities, the account exists but
  // cannot log in. Returning early on "exists" would leave it broken forever,
  // so repair instead of skipping.
  if (existing[0]?.exists) {
    await repairLoginUser(db, args);
    return 'exists';
  }

  // pgcrypto's schema varies by install; ask rather than assume.
  const ext = await db.query<{ nspname: string }>(
    `SELECT n.nspname FROM pg_extension e
       JOIN pg_namespace n ON n.oid = e.extnamespace
      WHERE e.extname = 'pgcrypto'`,
  );
  const cryptSchema = ext[0]?.nspname ?? 'public';

  const claims = {
    provider: 'email',
    providers: ['email'],
    operator_id: args.operatorId,
    role: args.role,
    claims: { operator_id: args.operatorId, role: args.role },
  };

  // Atomic: an auth.users row without its identity is an account that
  // exists but cannot log in.
  await db.transaction(async (tx) => {
    await tx.query(
      `INSERT INTO auth.users (
         id, instance_id, aud, role, email, encrypted_password, email_confirmed_at,
         raw_app_meta_data, raw_user_meta_data, created_at, updated_at,
         confirmation_token, recovery_token,
         email_change, email_change_token_new, email_change_token_current
       ) VALUES (
         $1, $2, 'authenticated', 'authenticated', $3,
         ${cryptSchema}.crypt($4, ${cryptSchema}.gen_salt('bf', 10)),
         now(), $5::jsonb, $6::jsonb, now(), now(), '', '', '', '', ''
       )`,
      [
        args.id,
        GOTRUE_INSTANCE_ID,
        args.email,
        args.password ?? QA_PASSWORD,
        JSON.stringify(claims),
        JSON.stringify({ full_name: args.fullName }),
      ],
    );

    await tx.query(
      // provider_id is text and user_id is uuid; reusing one placeholder for both
      // makes Postgres fail with "inconsistent types deduced for parameter $1".
      `INSERT INTO auth.identities (
         id, user_id, identity_data, provider, provider_id,
         last_sign_in_at, created_at, updated_at
       ) VALUES (
         gen_random_uuid(), $1::uuid, $2::jsonb, 'email', $3::text, now(), now(), now()
       )`,
      [
        args.id,
        JSON.stringify({
          sub: args.id,
          email: args.email,
          email_verified: true,
          phone_verified: false,
        }),
        args.id,
      ],
    );

    // handle_new_user inserts permissions='{}' — apply the role mapping.
    await tx.query(
      `UPDATE public.users SET permissions = $2::text[]
        WHERE email = $1 AND deleted_at IS NULL`,
      [args.email, args.permissions],
    );

  });

  return 'created';
}
