import { describe, it, expect, vi } from 'vitest';
import { render, screen } from '@testing-library/react';
import { DockLabel } from './DockLabel';

vi.mock('bwip-js/browser', () => ({
  default: {
    // Mirror real bwip-js output: viewBox only, no width/height attributes.
    toSVG: (opts: { text: string }) =>
      `<svg data-testid="bwipjs-svg" data-text="${opts.text}" viewBox="0 0 232 72" xmlns="http://www.w3.org/2000/svg"><rect /></svg>`,
  },
}));

describe('DockLabel', () => {
  it('renders the dock code prominently', () => {
    render(<DockLabel code="DOCK-001" name="Santiago Oriente" />);
    // Should appear at least twice — big code + barcode caption
    expect(screen.getAllByText('DOCK-001').length).toBeGreaterThanOrEqual(2);
  });

  it('renders the dock name in the header band', () => {
    render(<DockLabel code="DOCK-001" name="Santiago Oriente" />);
    expect(screen.getByText('Santiago Oriente')).toBeInTheDocument();
  });

  it('renders an Andén label', () => {
    render(<DockLabel code="DOCK-001" name="Santiago Oriente" />);
    expect(screen.getByText(/andén/i)).toBeInTheDocument();
  });

  it('embeds a Code128 SVG generated by bwip-js for the dock code', () => {
    const { container } = render(<DockLabel code="DOCK-007" name="Santiago FRU Norte" />);
    const svg = container.querySelector('[data-testid="bwipjs-svg"]') as SVGElement | null;
    expect(svg).not.toBeNull();
    expect(svg!.getAttribute('data-text')).toBe('DOCK-007');
  });

  it.each([
    ['compact', true],
    ['non-compact (print)', false],
  ])('forces the barcode SVG to fill its wrapper in %s mode', (_label, compact) => {
    // Regression: bwip-js emits viewBox-only SVG; without explicit width/height
    // and preserveAspectRatio="none" the browser keeps the intrinsic ratio and
    // the barcode overflows its wrapper — in compact mode that broke the modal,
    // in non-compact mode it pushed the print label onto a second page.
    const { container } = render(
      <DockLabel code="DOCK-012" name="Santiago Centro" compact={compact} />,
    );
    const svg = container.querySelector('[data-testid="bwipjs-svg"]') as SVGElement | null;
    expect(svg).not.toBeNull();
    expect(svg!.getAttribute('preserveAspectRatio')).toBe('none');
    expect(svg!.getAttribute('width')).toBe('100%');
    expect(svg!.getAttribute('height')).toBe('100%');
  });
});
