import { describe, it, expect, vi } from 'vitest';
import { render, screen } from '@testing-library/react';
import { DockLabel } from './DockLabel';

vi.mock('bwip-js/browser', () => ({
  default: {
    toSVG: (opts: { text: string }) =>
      `<svg data-testid="bwipjs-svg" data-text="${opts.text}"><rect /></svg>`,
  },
}));

describe('DockLabel', () => {
  it('renders the dock code prominently', () => {
    render(<DockLabel code="DOCK-001" name="Santiago Oriente" />);
    // Should appear at least twice — big code + barcode caption
    expect(screen.getAllByText('DOCK-001').length).toBeGreaterThanOrEqual(2);
  });

  it('renders the dock name in the header band', () => {
    render(<DockLabel code="DOCK-001" name="Santiago Oriente" />);
    expect(screen.getByText('Santiago Oriente')).toBeInTheDocument();
  });

  it('renders an Andén label', () => {
    render(<DockLabel code="DOCK-001" name="Santiago Oriente" />);
    expect(screen.getByText(/andén/i)).toBeInTheDocument();
  });

  it('embeds a Code128 SVG generated by bwip-js for the dock code', () => {
    const { container } = render(<DockLabel code="DOCK-007" name="Santiago FRU Norte" />);
    const svg = container.querySelector('[data-testid="bwipjs-svg"]') as SVGElement | null;
    expect(svg).not.toBeNull();
    expect(svg!.getAttribute('data-text')).toBe('DOCK-007');
  });
});
